### ISSUE TITLE
How to increase maxium event on logstash

### ISSUE THREAD

**Issue by shidex** [jswidler/elasticsearch-kubed#10]
Hi, I try using logstash but if icheck on elasticsearch using kibana maximum event just 600 event/second. if i try using elk non kubernetes cluster event can be 2k-5k

thanks

**Comment by jswidler** [comment]
I wrote a blog post that is meant to help you, but if you read the post and still have problems, I cannot help from this description.  There is no reason for performance to be so low.  Are you just on one computer.  If so, running multiple ES instances per computer probably hurts performance.  There is very little reason to run more than one ES instance per machine.
