### ISSUE TITLE
config should allow user to add in name of storage class

### ISSUE THREAD

**Issue by evannorstrand** [jswidler/elasticsearch-kubed#4]
config should allow user to add in name of storage class, in my case we want to use the ceph-block-storage .

**Comment by jswidler** [comment]
This is a demo project to help people get started, and I want it to match the blog post I wrote when I released it.  I hope you can learn from it either fork it or just save the output of the config script and use it as a starting place, customizing it as you need from there.  I'm going to close this issue, but if someone submitted a well crafted PR I might accept it.
