### ISSUE TITLE
Error Converting YAML to JSON

### ISSUE THREAD

**Issue by rjluzardo** [jswidler/elasticsearch-kubed#7]
Hey Guys,

I am trying to install ELK in Kubernetes on a Openstack environment. I am following the instructions on the document below but I am getting the following error when I try to start elasticsearch from the template.

Doc: 

https://engineering.udacity.com/high-performance-elk-with-kubernetes-part-1-1d09f41a4ce2

Error:

kubectl apply -f 2_elasticsearch
error parsing 2_elasticsearch/es-config.yml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"namespace":interface {}(nil)}
error parsing 2_elasticsearch/es-data.yml: error converting YAML to JSON: yaml: line 140: did not find expected key
error parsing 2_elasticsearch/es-master.yml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"namespace":interface {}(nil)}
error parsing 2_elasticsearch/es-services.yml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"namespace":interface {}(nil)}

I had the same issue with the namespace template and I resolved it creating the namespace manually. 

Any sugestion?

Thanks

Raul

**Comment by jswidler** [comment]
The templates are not meant to be used directly; did you run the `config-templates.py` script and use the output of that?
